trigger:
- main  # Change this to match your branch

pool:
  name: Default  # Use a Windows agent

steps:
- checkout: self
  persistCredentials: true

- task: AzureRmWebAppDeployment@4
  displayName: 'Deploy to Azure Web App'
  inputs:
    azureSubscription: 'MyWebAppSC'  # Connect this to your Azure subscription
    appType: 'webApp'
    WebAppName: 'MyDemoADO'  # Name of your Azure Web App
    packageForLinux: '$(Build.SourcesDirectory)'  # Path to your GitHub repository
    enableCustomDeployment: true
    authenticationMethod: 'Basic'  # Specify basic authentication method for FTPS
    username: '$(FTPUsername)'  # Specify your FTPS username (either application or user scope)
    password: '$(FTPPassword)'  # Specify your FTPS password (either application or user scope)
