# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: Default
steps:
- checkout: self
  persistCredentials: true  
- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'MyWebAppSC'
    appType: 'webAppLinux'
    WebAppName: 'MyDemoADO'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'

