trigger:
- main  # Change this to match your branch

pool:
  name: Default  # Use a Windows agent

steps:
- checkout: self
  persistCredentials: true

- task: AzureRmWebAppDeployment@4
  displayName: 'Deploy to Azure Web App'
  inputs:
    azureSubscription: 'testintegration'  # Connect this to your Azure subscription
    appType: 'webApp'
    WebAppName: 'karthik2-webapp'  # Name of your Azure Web App
    packageForLinux: '$(Build.SourcesDirectory)'  # Path to your GitHub repository
    enableCustomDeployment: true
